### ISSUE TITLE
Is any Chinese portal website ?

### ISSUE THREAD

**Issue by magixsource** [OpenFunction/OpenFunction#113]
WHy not build a portal site to intro openfunction?   What diff of openFaas and OpenFunction。Thanks a ton.

**Comment by tpiperatgod** [comment]
Hi, we are working on the OpenFunction [website](https://github.com/OpenFunction/website), which you can see in the latest [PR](https://github.com/OpenFunction/website/pull/6) that I have submitted some of the English documentation, and I will submit the corresponding Chinese documentation soon.

Regarding the comparison between OpenFaaS and OpenFunction, I personally consider that OpenFunction is designed to integrate some trending technologies like Shipwright, KEDA, Dapr, etc. to build a new serverless framework, specifically oriented to use [buildpacks](https://buildpacks.io/) instead of Dockerfile to build images. Using Dapr+KEDA for event-driven dynamically scalable workloads, the ability to serving its own components with its own serverless capabilities (in development), etc.

For now, however, there are still gaps between OpenFunction and these mature serverless frameworks, and we are working to bridge those gaps. Hope this can help you :grinning:

**Comment by tpiperatgod** [comment]
You can view our [roadmap](https://github.com/OpenFunction/OpenFunction/blob/main/docs/roadmap.md) to see our plans.

**Comment by benjaminhuo** [comment]
> WHy not build a portal site to intro openfunction? What diff of openFaas and OpenFunction。Thanks a ton.

OpenFunction has late-mover advantage over OpenFaaS and will eventually get its place in the FaaS area.

**Comment by magixsource** [comment]
Good Jobs and Thanks!  @tpiperatgod @benjaminhuo :)

**Comment by FeynmanZhou** [comment]
The Chinese version is available: https://openfunction.dev/zh/
