### ISSUE TITLE
Add OpenFunction Katacoda scenario

### ISSUE THREAD

**Issue by tpiperatgod** [OpenFunction/OpenFunction#167]
**Description**
We could add a **Katacoda scenario** for OpenFunction. Like https://www.katacoda.com/kubesphere/

This helps to demonstrate OpenFunction quickly and makes sense if the user lacks the cluster resources.

**Additional context**
https://www.katacoda.com/kubesphere/

**Comment by FeynmanZhou** [comment]
> /assign @x893675

Hi @x893675 ,

Thanks for your interest! We could collaborate with you to finish it. The [previous Katacoda scenarios](https://www.katacoda.com/kubesphere/) were developed and contributed by [@AbdelouahabMbarki](https://github.com/AbdelouahabMbarki), he could also help out with this feature.

**Comment by x893675** [comment]
this [openfunction scenarious](https://www.katacoda.com/x893675)  can work now.

### Issue:

#### Version incompatibility 
    
> katacoda k8s version is v1.18.0
> openfunction latest version need k8s version >= v1.19.0
> knative (deploy.sh installed) need k8s >= v1.20.0
> nginx-ingress (deploy.sh installed) install failed  when k8s version is v1.19.0  [ingress-nginx#7810](https://github.com/kubernetes/ingress-nginx/issues/7810)

workaround:
1. upgrade k8s version to v1.19.0 when katacoda k8s env runtime start
2. only install cert-manager, Shipwright builder, OpenFuncAsync serving runtime

please create repo **katacoda-scenarios** in org OpenFunction, i will create a PR

**Comment by benjaminhuo** [comment]
@x893675 You can create a PR in the samples repo

**Comment by benjaminhuo** [comment]
Thanks for the contribution! @x893675

**Comment by FeynmanZhou** [comment]
> @FeynmanZhou, @tpiperatgod
> 
> this [openfunction scenarious](https://www.katacoda.com/x893675) can work now.
> 
> ### Issue:
> #### Version incompatibility
> > katacoda k8s version is v1.18.0
> > openfunction latest version need k8s version >= v1.19.0
> > knative (deploy.sh installed) need k8s >= v1.20.0
> > nginx-ingress (deploy.sh installed) install failed  when k8s version is v1.19.0  [ingress-nginx#7810](https://github.com/kubernetes/ingress-nginx/issues/7810)
> 
> workaround:
> 
> 1. upgrade k8s version to v1.19.0 when katacoda k8s env runtime start
> 2. only install cert-manager, Shipwright builder, OpenFuncAsync serving runtime
> 
> please create repo **katacoda-scenarios** in org OpenFunction, i will create a PR

Awesome, thanks for your contribution! Could you create a new folder in the [Sample repo](https://github.com/OpenFunction/samples). I will create a Katacoda URL with `katacoda.com/openfunction` later.

I noticed the issues of version incompatibility caused by the built-in Kubernetes version in Katacoda, but I am curious why the [Knative scenario](https://www.katacoda.com/javajon/courses/kubernetes-serverless/knative) can be used with Kubernetes 1.18.

IMO, the workaround should be added to the step-by-step guide of Katacoda scenario if we don't have a better solution so far.

**Comment by x893675** [comment]
> 

[Knative scenario](https://www.katacoda.com/javajon/courses/kubernetes-serverless/knative) use Knative v0.18.0, but [OpenFunction deploy.sh](https://github.com/OpenFunction/OpenFunction/blob/main/hack/deploy.sh) use Knative v0.26.0.

Knative [require Kubernetes 1.20 since v0.25.0](https://github.com/knative/serving/releases)

The highest k8s version that katacoda can be upgraded through `apt-install`  is v1.19.4. I think we can manually upgrade k8s to a newer version(1.20, 1.21... etc)

I will move the upgrade operation to step and create pr to [Sample repo](https://github.com/OpenFunction/samples) later

**Comment by tpiperatgod** [comment]
Close this issue since the OpenFunction Katacode scenarios works now.
