### ISSUE TITLE
Integration with Apache EventMesh

### ISSUE THREAD

**Issue by xwm1992** [OpenFunction/OpenFunction#480]
**Proposal**
If you have a detailed proposal, you can also submit it via pull request

An outline of the proposal is provided here for reference:

- Motivation
  Currently, OpenFunction injects the dapr sidecar into each Function pod, which can be plugged in and replaced with EventMesh Connector to achieve integrated interaction with EventMesh.

- Goals
  Integrate OpenFunction with Apache EventMesh 

- Example
![openfunction-proposal](https://github.com/OpenFunction/OpenFunction/assets/13237619/c4a24965-be8b-4a76-811c-b4067233ea95)

- Action Items
  Adjust functions-framework-java module.
  Support EventMesh trigger as one of the triggers plugin.
  Get the trigger configuration from the function context.

**Comment by benjaminhuo** [comment]
Looks feasible.

Is it possible to use something like [dapr standalone mode](https://openfunction.dev/docs/concepts/baas_integration) instead of sidecar mode?

In [dapr standalone mode](https://openfunction.dev/docs/concepts/baas_integration) mode, it needn't inject one sidecar to each pod. Instead, all pods of a function share one single "EventMesh OpenFunction Connector"

**Comment by xwm1992** [comment]
> dapr standalone mode


For EventMesh OpenFunction Connector, we currently have the concept of `groups`. I understand that the goal we hope to achieve is that the function instances in the group are equal, and a group of function instances share a Connector. I also need to have a certain understanding of the existing `dapr standalone mode` to ensure the same semantics.
