### ISSUE TITLE
Failed to install using Helm on EKS

### ISSUE THREAD

**Issue by smartboy37597** [OpenFunction/OpenFunction#509]
**Description**

When I followed the installation process on the official website, I encountered the following error:
```shell
# helm repo add openfunction https://openfunction.github.io/charts/
# helm repo update
# kubectl create namespace openfunction
# helm install openfunction openfunction/openfunction -n openfunction
helm install openfunction openfunction/openfunction -n openfunction
E1114 23:35:20.136791   29329 request.go:1092] Unexpected error when reading response body: net/http: request canceled (Client.Timeout or context cancellation while reading body)
E1114 23:35:20.137127   29329 round_tripper.go:63] CancelRequest not implemented by *cli.retryingRoundTripper
E1114 23:35:53.335274   29329 round_tripper.go:63] CancelRequest not implemented by *cli.retryingRoundTripper
E1114 23:35:53.335406   29329 request.go:1092] Unexpected error when reading response body: net/http: request canceled (Client.Timeout or context cancellation while reading body)
E1114 23:36:25.628197   29329 round_tripper.go:63] CancelRequest not implemented by *cli.retryingRoundTripper
E1114 23:36:25.628319   29329 request.go:1092] Unexpected error when reading response body: net/http: request canceled (Client.Timeout or context cancellation while reading body)
W1114 23:38:06.337436   29329 warnings.go:70] The v1alpha2 version of Gateway has been deprecated and will be removed in a future release of the API. Please upgrade to v1beta1.
W1114 23:38:08.479749   29329 warnings.go:70] The v1alpha2 version of GatewayClass has been deprecated and will be removed in a future release of the API. Please upgrade to v1beta1.
E1114 23:39:57.337403   29329 round_tripper.go:63] CancelRequest not implemented by *cli.retryingRoundTripper
E1114 23:39:57.337570   29329 request.go:1092] Unexpected error when reading response body: net/http: request canceled (Client.Timeout or context cancellation while reading body)
E1114 23:41:37.544118   29329 round_tripper.go:63] CancelRequest not implemented by *cli.retryingRoundTripper
E1114 23:41:37.544274   29329 request.go:1092] Unexpected error when reading response body: net/http: request canceled (Client.Timeout or context cancellation while reading body)
```

**Environmental**
I installed Helm and kubectl locally and operated on the k8s cluster in AWS EKS.
- AWS EKS kubernetes version: 1.28
- OpenFunction version: latest
- CHART PATH: /Users/Library/Caches/helm/repository/openfunction-v1.2.0-v0.7.0.tgz
- helm version v3.12.3

**Expected behavior**

**Actual behavior**

**To Reproduce**

**Screenshots**
<img width="1190" alt="image" src="https://github.com/OpenFunction/OpenFunction/assets/47653926/cacda132-deaf-4793-af88-088887ec103b">

**Additional context**

**Comment by aryasoni98** [comment]
I would like to work on it. Please assign me .

**Comment by benjaminhuo** [comment]
> I would like to work on it. Please assign me .

Great, thanks @aryasoni98

**Comment by smartboy37597** [comment]
Thanks for your reply, I have successfully installed Openfunction by changing computers.

But I'm having a problem deploying [sample](https://github.com/OpenFunction/samples/tree/main/functions/knative/hello-world-go) `knative/hello-world-go` now, I registered my account on docker hub, created my repository, `push-secret` was created, but I don't know what to fill in for `<your registry name>` as mentioned here, I tried to fill in `my_duckerhub_username/my_repo_name` but it says **not found** at the **ANALYZING** stage, and the step-create container is stuck at **BUILDING**.

This is my configuration:

<img width="554" alt="image" src="https://github.com/OpenFunction/OpenFunction/assets/47653926/a81b1cde-ff23-48ad-a88e-e174bb0ba485">

<img width="1168" alt="image" src="https://github.com/OpenFunction/OpenFunction/assets/47653926/85da1aef-1b35-4d16-a12e-99e05e94d3fb">

<img width="820" alt="image" src="https://github.com/OpenFunction/OpenFunction/assets/47653926/fc549251-8b65-454f-a3bd-350cab2e4141">

I'm wondering if this has something to do with me incorrectly filling in <your registry name> or if it's something else.

**Comment by aryasoni98** [comment]
@smartboy37597 

When you are setting up your Docker image in a Kubernetes manifest file and it asks for <your registry name>, you typically need to fill in the URL of the Docker registry where your image is located followed by the image name and tag.

Here's the format you should use:
`<registry-url>/<username>/<repository>:<tag>`

For Docker Hub, the <registry-url> is usually docker.io. Your username is your Docker Hub username, <repository> is the name of the repository you created on Docker Hub, and <tag> is the version tag you assigned to your image.

So if your Docker Hub username is my_dockerhub_username and your repository is named my_repo_name, and you are pushing an image with the tag v1, you would fill in:

`docker.io/my_dockerhub_username/my_repo_name:v1`

----------

The issue indicated by "Previous image with name '...' not found" during the build process typically suggests that the build system is trying to pull a base image for your function that does not exist or cannot be accessed with the provided credentials. This could be due to several reasons:

1. **Incorrect Image Name or Tag**: The base image name or tag might be incorrect in your function configuration. Double-check the image name and tag you are using.

2. **Private Registry Access**: If the base image is stored in a private registry, you need to ensure that your Kubernetes cluster has access to it through a correct `imagePullSecret`.

3. **Connectivity Issues**: There might be connectivity issues between your Kubernetes cluster and the image registry.

To troubleshoot this:

- Verify that the base image exists in the registry and is accessible.
- Make sure the `imageCredentials` specified in your configuration (`push-secret`) has the correct permissions to pull images from the registry where the base image is hosted.
- If you're referencing an image from a public registry and it's not found, ensure that there are no typos in the image name or tag and that the image has been pushed to the registry.
- Check the logs of your image builder and registry service for any additional clues as to why the image cannot be found.

If the issue persists, you may need to consult the documentation for the specific builder you are using or seek support from the community or maintainers of the project.

**Comment by smartboy37597** [comment]
@aryasoni98 
Thank you for your reply, according to your instruction, when I configured the Docker registry correctly, I have successfully run the `go-sample`.
I thought it might be due to the machine performance or network reason that the build time is too long, but finally after about 30 minutes it also builds.

**Comment by benjaminhuo** [comment]
@aryasoni98 @smartboy37597 Here is the guide to setup container registry:
https://openfunction.dev/docs/getting-started/quickstarts/prerequisites/#registry-credential
